[package]
name = "speaker-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.14.1"
serialport = "4.2"

[build-dependencies]
slint-build = "1.14.1"
